name: "asgard_data_products"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "asgard_data_products"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
log-path: "logs"

# Clean targets - directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Require explicit dbt version for consistency
require-dbt-version: [">=1.6.0", "<2.0.0"]

# Project variables
vars:
  # Environment configuration
  source_catalog: "iceberg"
  silver_schema: "silver"
  gold_schema: "gold"
  
  # Data product configuration
  data_product_prefix: "dp_"
  data_product_owner: "data-platform-team"
  data_product_environment: "{{ env_var('DBT_ENVIRONMENT', 'dev') }}"
  
  # Iceberg/S3 configuration
  iceberg_warehouse_path: "s3a://airbytedestination1/iceberg/"
  nessie_uri: "http://nessie.data-platform.svc.cluster.local:19120/api/v1"
  nessie_ref: "main"
  
  # Performance tuning
  compression_codec: "SNAPPY"
  target_file_size_mb: 256
  max_rows_per_partition: 1000000

# Configure model defaults
models:
  asgard_data_products:
    # Global model configurations
    +materialized: table
    +file_format: iceberg
    +on_schema_change: "fail"
    +full_refresh: false
    
    # Documentation settings
    +docs:
      show: true
    
    # Source/staging models (from silver layer)
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
      +tags: ["staging"]
    
    # Intermediate transformations
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
      +tags: ["intermediate"]
    
    # Final data products (gold layer)
    data_products:
      +materialized: table
      +file_format: iceberg
      +docs:
        node_color: "green"
      +tags: ["data_product", "gold_layer"]
      +table_properties:
        write.format.default: "parquet"
        write.parquet.compression-codec: "snappy"
        write.metadata.metrics.column.all: "full"
        write.metadata.metrics.default: "full"
        write.target-file-size-bytes: "268435456"  # 256MB
    
    # Metrics and aggregations
    metrics:
      +materialized: table
      +file_format: iceberg
      +docs:
        node_color: "purple"
      +tags: ["metrics"]

# Configure test defaults
tests:
  asgard_data_products:
    +severity: "error"
    +store_failures: true
    +store_failures_as: "table"

# Configure snapshot defaults
snapshots:
  asgard_data_products:
    +target_schema: "snapshots"
    +file_format: iceberg
    +check_cols: "all"
    +unique_key: "id"
    +strategy: "timestamp"

# Configure seeds
seeds:
  asgard_data_products:
    +materialized: table
    +file_format: iceberg

# Configure sources
sources:
  asgard_data_products:
    +meta:
      owner: "{{ var('data_product_owner') }}"
      environment: "{{ var('data_product_environment') }}"

# Analysis configuration
analysis:
  asgard_data_products:
    +docs:
      show: true