asgard_data_products:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: dbt
      host: trino.data-platform.svc.cluster.local
      port: 8080
      catalog: iceberg
      schema: gold
      threads: 4
      http_scheme: http

    prod:
      type: trino
      method: none
      user: dbt
      host: trino.data-platform.svc.cluster.local
      port: 8080
      catalog: iceberg
      schema: gold
      threads: 8
      http_scheme: http
      session_properties:
        iceberg.target-file-size-bytes: "268435456"
        iceberg.compression-codec: "SNAPPY"
