replicaCount: 1
namespace: asgard
image:
  repository: 637423187518.dkr.ecr.eu-north-1.amazonaws.com/asgard
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ecr-secret

env:
  ENVIRONMENT: "production"
  AIRBYTE_BASE_URL: "http://airbyte-airbyte-server-svc.airbyte.svc.cluster.local:8001/api/public/v1"
  PIPELINE_NAMESPACE: "asgard"
  SPARK_NAMESPACE: "asgard"
  SPARK_IMAGE: "637423187518.dkr.ecr.eu-north-1.amazonaws.com/spark-custom:latest"
  SPARK_SERVICE_ACCOUNT: "spark-sa"
  S3_SECRET_NAME: "s3-credentials"

serviceAccount:
  create: true
  name: "asgard-app"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP

ingress:                                              
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: asgard-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

## Note: this ingress is for public endpoints add all the paths under paths:, if there is no public path enabled: false
publicIngress:
  enabled: false
  host: asgard-public.local
  paths:
    - /docs

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
 