apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: data-platform
  annotations:
    description: "Auto-refresh ECR secret using IAM roles"
spec:
  # Run every 12 hours (at 00:00 and 12:00)
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-secret-updater
          containers:
            - name: ecr-secret-updater
              image: amazon/aws-cli:latest
              command:
                - /bin/sh
                - -c
                - |
                  # Get ECR login token
                  TOKEN=$(aws ecr get-login-password --region eu-north-1)

                  # Delete existing secret if it exists
                  kubectl delete secret ecr-secret --ignore-not-found=true -n data-platform

                  # Create new secret with fresh token
                  kubectl create secret docker-registry ecr-secret \
                    --docker-server=637423187518.dkr.ecr.eu-north-1.amazonaws.com \
                    --docker-username=AWS \
                    --docker-password="$TOKEN" \
                    --docker-email=amrit@faralpha.com \
                    -n data-platform

                  echo "ECR secret refreshed successfully at $(date)"
              env:
                - name: AWS_DEFAULT_REGION
                  value: "eu-north-1"
              # No AWS credentials needed - uses IAM role
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
