apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-updater
  namespace: asgard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: asgard
  name: ecr-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-manager-binding
  namespace: asgard
subjects:
  - kind: ServiceAccount
    name: ecr-secret-updater
    namespace: asgard
roleRef:
  kind: Role
  name: ecr-secret-manager
  apiGroup: rbac.authorization.k8s.io
