apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: asgard
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log","services","configmaps","persistentvolumeclaims","secrets"]
    verbs: ["get","list","watch","create","delete","deletecollection","patch","update"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch","create","delete","patch","update"]
