version: 2

models:
  - name: dp_customer_360
    description: "Comprehensive customer data product with 360-degree customer view"
    meta:
      data_product_type: "CUSTOMER_360"
      owner: "data-platform-team"
      update_frequency: "daily"
      consumers: ["analytics_team", "marketing_team", "customer_success"]

    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address"
        tests:
          - not_null
      - name: customer_segment
        description: "Customer value segmentation"
        tests:
          - accepted_values:
              values:
                ["HIGH_VALUE", "MEDIUM_VALUE", "LOW_VALUE", "NO_PURCHASES"]
      - name: customer_status
        description: "Customer lifecycle status"
        tests:
          - accepted_values:
              values: ["ACTIVE", "AT_RISK", "CHURNED", "NEVER_PURCHASED"]

  - name: dp_product_performance
    description: "Product performance analytics data product"
    meta:
      data_product_type: "PRODUCT_PERFORMANCE"
      owner: "data-platform-team"
      update_frequency: "daily"
      consumers: ["product_team", "sales_team", "analytics_team"]

    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: performance_tier
        description: "Product performance classification"
        tests:
          - accepted_values:
              values:
                ["TOP_PERFORMER", "GOOD_PERFORMER", "LOW_PERFORMER", "NO_SALES"]

  - name: dp_revenue_analytics
    description: "Monthly revenue analytics and trends data product"
    meta:
      data_product_type: "REVENUE_ANALYTICS"
      owner: "data-platform-team"
      update_frequency: "monthly"
      consumers: ["finance_team", "executive_team", "analytics_team"]

    columns:
      - name: transaction_month
        description: "Month of transactions"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue for the month"
        tests:
          - not_null
      - name: growth_trend
        description: "Revenue growth trend classification"
        tests:
          - accepted_values:
              values: ["HIGH_GROWTH", "GROWTH", "STABLE", "DECLINING"]
